/* The following code was generated by JFlex 1.4.3 on 23/03/17 1:07 */

package Modelos;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 23/03/17 1:07 from the specification file
 * <tt>Lexer.flex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\10\1\6\1\0\1\10\1\7\22\0\1\4\1\0\1\3"+
    "\5\0\1\43\1\44\5\0\1\5\1\1\1\20\1\21\7\1\1\0"+
    "\1\41\1\11\1\42\1\16\2\0\1\13\1\36\1\22\1\32\1\15"+
    "\1\47\1\14\1\17\1\25\1\2\1\23\1\24\1\34\1\31\1\30"+
    "\1\12\1\2\1\33\1\26\1\27\1\40\1\37\1\45\1\46\1\35"+
    "\1\2\6\0\1\13\1\36\1\22\1\32\1\15\1\47\1\14\1\17"+
    "\1\25\1\2\1\23\1\24\1\34\1\31\1\30\1\12\1\2\1\33"+
    "\1\26\1\27\1\40\1\37\1\45\1\46\1\35\1\2\1\50\1\0"+
    "\1\51\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\1\1\2\2\4\1\2\1\5"+
    "\15\1\1\6\1\7\1\10\1\11\2\1\1\12\1\13"+
    "\1\0\1\14\6\0\3\1\1\15\1\16\6\1\1\17"+
    "\17\1\12\0\24\1\1\20\7\1\12\0\3\1\1\21"+
    "\1\22\3\1\1\23\4\1\1\24\5\1\1\25\4\1"+
    "\1\26\2\1\2\27\6\0\1\30\1\0\3\1\1\31"+
    "\1\32\1\1\1\33\1\1\1\34\1\35\1\36\11\1"+
    "\1\37\1\40\2\0\1\41\1\0\1\42\1\43\1\44"+
    "\2\1\1\45\1\46\2\1\1\47\1\50\1\51\1\52"+
    "\1\53\1\1\1\54\1\55\1\56\1\57\1\60\2\1"+
    "\1\61\1\62\1\1\1\63\1\0\1\64\2\0\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[207];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\52\0\322\0\374"+
    "\0\u0126\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c"+
    "\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348\0\52\0\52"+
    "\0\52\0\52\0\u0372\0\u039c\0\52\0\52\0\u03c6\0\52"+
    "\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\u04c2\0\u04ec\0\u0516"+
    "\0\u0540\0\176\0\176\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612"+
    "\0\u063c\0\176\0\u0666\0\u0690\0\u06ba\0\u06e4\0\u070e\0\u0738"+
    "\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\u0834\0\u085e\0\u0888"+
    "\0\u08b2\0\u08dc\0\u0906\0\u0930\0\u095a\0\u0984\0\u09ae\0\u09d8"+
    "\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4\0\u0afe\0\u0b28"+
    "\0\u0b52\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa\0\u0c24\0\u0c4e\0\u0c78"+
    "\0\u0ca2\0\u0ccc\0\u0cf6\0\u0d20\0\u0d4a\0\u0d74\0\u0d9e\0\176"+
    "\0\u0dc8\0\u0df2\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a\0\u0ec4\0\u0eee"+
    "\0\u0f18\0\u0f42\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea\0\u1014\0\u103e"+
    "\0\u1068\0\u1092\0\u10bc\0\u10e6\0\176\0\176\0\u1110\0\u113a"+
    "\0\u1164\0\176\0\u118e\0\u11b8\0\u11e2\0\u120c\0\176\0\u1236"+
    "\0\u1260\0\u128a\0\u12b4\0\u12de\0\176\0\u1308\0\u1332\0\u135c"+
    "\0\u1386\0\u13b0\0\u13da\0\u1404\0\52\0\u08dc\0\u142e\0\u1458"+
    "\0\u1482\0\u14ac\0\u14d6\0\u1500\0\52\0\u152a\0\u1554\0\u157e"+
    "\0\u15a8\0\176\0\176\0\u15d2\0\176\0\u15fc\0\176\0\176"+
    "\0\176\0\u1626\0\u1650\0\u167a\0\u16a4\0\u16ce\0\u16f8\0\u1722"+
    "\0\u174c\0\u1776\0\176\0\176\0\u17a0\0\u17ca\0\52\0\u17f4"+
    "\0\52\0\52\0\52\0\u181e\0\u1848\0\176\0\176\0\u1872"+
    "\0\u189c\0\176\0\176\0\176\0\176\0\176\0\u18c6\0\176"+
    "\0\176\0\52\0\52\0\52\0\u18f0\0\u191a\0\176\0\176"+
    "\0\u1944\0\176\0\u196e\0\176\0\u1998\0\u19c2\0\52";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[207];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\2\1\6\1\7"+
    "\1\6\1\10\1\11\3\4\1\2\1\12\2\3\1\13"+
    "\1\4\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\2\4\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\4\1\34\1\35\1\36\53\0\1\3"+
    "\1\4\7\0\4\4\1\0\1\4\2\3\17\4\4\0"+
    "\3\4\3\0\2\4\7\0\4\4\1\0\22\4\4\0"+
    "\3\4\4\0\1\37\1\40\1\37\1\41\4\0\4\37"+
    "\1\0\1\37\2\0\17\37\4\0\3\37\10\0\1\6"+
    "\50\0\1\42\4\0\1\43\4\0\1\44\12\0\1\45"+
    "\3\0\1\46\14\0\2\4\7\0\1\4\1\47\2\4"+
    "\1\0\14\4\1\50\5\4\4\0\3\4\3\0\2\4"+
    "\7\0\3\4\1\51\1\0\1\4\1\52\1\53\11\4"+
    "\1\54\5\4\4\0\3\4\3\0\2\4\7\0\4\4"+
    "\1\0\1\55\4\4\1\56\6\4\1\57\5\4\4\0"+
    "\3\4\3\0\2\4\7\0\4\4\1\0\6\4\1\60"+
    "\13\4\4\0\3\4\3\0\2\4\7\0\4\4\1\0"+
    "\12\4\1\61\1\62\1\4\1\63\4\4\4\0\3\4"+
    "\3\0\2\4\7\0\4\4\1\0\10\4\1\64\11\4"+
    "\4\0\3\4\3\0\2\4\7\0\3\4\1\65\1\0"+
    "\6\4\1\66\13\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\12\4\1\67\7\4\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\21\4\1\70\4\0\3\4"+
    "\3\0\2\4\7\0\3\4\1\71\1\0\22\4\4\0"+
    "\3\4\3\0\2\4\7\0\3\4\1\72\1\0\22\4"+
    "\4\0\3\4\3\0\2\4\7\0\4\4\1\0\6\4"+
    "\1\73\12\4\1\74\4\0\3\4\3\0\2\4\7\0"+
    "\1\4\1\75\2\4\1\0\22\4\4\0\3\4\3\0"+
    "\2\4\7\0\1\76\3\4\1\0\7\4\1\77\12\4"+
    "\4\0\3\4\3\0\2\4\7\0\4\4\1\0\6\4"+
    "\1\100\13\4\4\0\3\4\3\0\2\4\7\0\4\4"+
    "\1\0\11\4\1\101\10\4\4\0\3\4\4\0\1\37"+
    "\1\40\1\37\5\0\4\37\1\0\1\37\2\0\17\37"+
    "\4\0\3\37\2\0\2\102\1\103\1\102\2\103\1\0"+
    "\3\102\4\103\1\102\1\103\2\102\17\103\4\102\3\103"+
    "\2\102\12\0\1\104\4\0\1\105\12\0\1\106\3\0"+
    "\1\107\26\0\1\110\53\0\1\111\61\0\1\112\54\0"+
    "\1\113\22\0\2\4\7\0\4\4\1\0\7\4\1\114"+
    "\12\4\4\0\3\4\3\0\2\4\7\0\4\4\1\0"+
    "\6\4\1\115\13\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\6\4\1\116\13\4\4\0\3\4\3\0"+
    "\2\4\7\0\3\4\1\117\1\0\22\4\4\0\3\4"+
    "\3\0\2\4\7\0\1\4\1\120\1\4\1\121\1\0"+
    "\22\4\4\0\3\4\3\0\2\4\7\0\1\4\1\122"+
    "\2\4\1\0\22\4\4\0\3\4\3\0\2\4\7\0"+
    "\3\4\1\123\1\0\22\4\4\0\3\4\3\0\2\4"+
    "\7\0\4\4\1\0\7\4\1\124\12\4\4\0\3\4"+
    "\3\0\2\4\7\0\1\125\3\4\1\0\3\4\1\126"+
    "\16\4\4\0\3\4\3\0\2\4\7\0\1\4\1\127"+
    "\2\4\1\0\22\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\16\4\1\130\3\4\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\22\4\4\0\1\4\1\131"+
    "\1\4\3\0\2\4\7\0\4\4\1\0\10\4\1\132"+
    "\11\4\4\0\3\4\3\0\2\4\7\0\4\4\1\0"+
    "\3\4\1\133\1\4\1\134\14\4\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\15\4\1\135\4\4\4\0"+
    "\3\4\3\0\2\4\7\0\4\4\1\0\5\4\1\136"+
    "\14\4\4\0\3\4\3\0\2\4\7\0\1\4\1\137"+
    "\2\4\1\0\22\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\10\4\1\140\11\4\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\10\4\1\141\11\4\4\0"+
    "\3\4\3\0\2\4\7\0\4\4\1\0\5\4\1\142"+
    "\6\4\1\143\5\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\13\4\1\144\6\4\4\0\3\4\3\0"+
    "\2\4\7\0\3\4\1\145\1\0\22\4\4\0\3\4"+
    "\3\0\2\4\7\0\4\4\1\0\13\4\1\146\6\4"+
    "\4\0\3\4\3\0\2\4\7\0\4\4\1\0\3\4"+
    "\1\147\16\4\4\0\3\4\4\0\1\150\7\0\4\150"+
    "\1\0\1\150\2\0\17\150\4\0\3\150\2\0\2\102"+
    "\1\151\1\102\2\103\1\0\3\102\4\151\1\102\1\151"+
    "\2\102\17\151\4\102\3\151\2\102\13\0\1\152\53\0"+
    "\1\153\61\0\1\154\54\0\1\155\35\0\1\156\50\0"+
    "\1\157\75\0\1\160\44\0\1\161\20\0\2\4\7\0"+
    "\4\4\1\0\7\4\1\162\12\4\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\15\4\1\163\4\4\4\0"+
    "\3\4\3\0\2\4\7\0\2\4\1\164\1\4\1\0"+
    "\22\4\4\0\3\4\3\0\2\4\7\0\4\4\1\0"+
    "\22\4\4\0\2\4\1\165\3\0\2\4\7\0\4\4"+
    "\1\0\14\4\1\166\5\4\4\0\3\4\3\0\2\4"+
    "\7\0\4\4\1\0\3\4\1\167\16\4\4\0\3\4"+
    "\3\0\2\4\7\0\4\4\1\0\7\4\1\170\12\4"+
    "\4\0\3\4\3\0\2\4\7\0\1\4\1\171\2\4"+
    "\1\0\22\4\4\0\3\4\3\0\2\4\7\0\4\4"+
    "\1\0\10\4\1\172\11\4\4\0\3\4\3\0\2\4"+
    "\7\0\4\4\1\0\21\4\1\173\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\5\4\1\174\14\4\4\0"+
    "\3\4\3\0\2\4\7\0\2\4\1\175\1\4\1\0"+
    "\22\4\4\0\3\4\3\0\2\4\7\0\4\4\1\0"+
    "\5\4\1\176\14\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\10\4\1\177\11\4\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\5\4\1\200\14\4\4\0"+
    "\3\4\3\0\2\4\7\0\4\4\1\0\5\4\1\201"+
    "\14\4\4\0\3\4\3\0\2\4\7\0\4\4\1\0"+
    "\11\4\1\202\10\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\17\4\1\203\2\4\4\0\3\4\3\0"+
    "\2\4\7\0\3\4\1\204\1\0\22\4\4\0\3\4"+
    "\3\0\2\4\7\0\4\4\1\0\13\4\1\205\6\4"+
    "\4\0\3\4\3\0\2\4\7\0\4\4\1\0\10\4"+
    "\1\206\11\4\4\0\3\4\3\0\2\4\7\0\4\4"+
    "\1\0\21\4\1\207\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\3\4\1\210\16\4\4\0\3\4\3\0"+
    "\2\4\7\0\1\4\1\211\2\4\1\0\22\4\4\0"+
    "\3\4\3\0\2\4\7\0\4\4\1\0\14\4\1\212"+
    "\5\4\4\0\3\4\3\0\2\4\7\0\4\4\1\0"+
    "\10\4\1\213\11\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\21\4\1\214\4\0\3\4\4\0\1\150"+
    "\1\215\6\0\4\150\1\0\1\150\2\0\17\150\4\0"+
    "\3\150\2\0\2\102\1\151\1\216\2\103\1\0\3\102"+
    "\4\151\1\102\1\151\2\102\17\151\4\102\3\151\2\102"+
    "\14\0\1\217\50\0\1\220\75\0\1\221\44\0\1\222"+
    "\34\0\1\223\66\0\1\224\35\0\1\225\70\0\1\226"+
    "\15\0\2\4\7\0\4\4\1\0\22\4\4\0\1\227"+
    "\2\4\3\0\2\4\7\0\1\4\1\230\2\4\1\0"+
    "\22\4\4\0\3\4\3\0\2\4\7\0\4\4\1\0"+
    "\1\231\21\4\4\0\3\4\3\0\2\4\7\0\4\4"+
    "\1\0\4\4\1\232\15\4\4\0\3\4\3\0\2\4"+
    "\7\0\4\4\1\0\7\4\1\233\12\4\4\0\3\4"+
    "\3\0\2\4\7\0\4\4\1\0\10\4\1\234\11\4"+
    "\4\0\3\4\3\0\2\4\7\0\4\4\1\0\10\4"+
    "\1\235\11\4\4\0\3\4\3\0\2\4\7\0\4\4"+
    "\1\0\21\4\1\236\4\0\3\4\3\0\2\4\7\0"+
    "\3\4\1\237\1\0\22\4\4\0\3\4\3\0\2\4"+
    "\7\0\3\4\1\240\1\0\22\4\4\0\3\4\3\0"+
    "\2\4\7\0\3\4\1\241\1\0\22\4\4\0\3\4"+
    "\3\0\2\4\7\0\4\4\1\0\6\4\1\242\13\4"+
    "\4\0\3\4\3\0\2\4\7\0\1\4\1\243\2\4"+
    "\1\0\22\4\4\0\3\4\3\0\2\4\7\0\3\4"+
    "\1\244\1\0\22\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\10\4\1\245\11\4\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\11\4\1\246\10\4\4\0"+
    "\3\4\3\0\2\4\7\0\3\4\1\247\1\0\22\4"+
    "\4\0\3\4\3\0\2\4\7\0\4\4\1\0\1\250"+
    "\21\4\4\0\3\4\3\0\2\4\7\0\4\4\1\0"+
    "\10\4\1\251\11\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\6\4\1\252\13\4\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\1\253\21\4\4\0\3\4"+
    "\3\0\2\4\7\0\4\4\1\0\7\4\1\254\12\4"+
    "\4\0\3\4\17\0\1\255\66\0\1\256\35\0\1\257"+
    "\70\0\1\260\32\0\1\261\51\0\1\262\51\0\1\263"+
    "\34\0\2\4\7\0\4\4\1\0\11\4\1\264\10\4"+
    "\4\0\3\4\3\0\2\4\7\0\4\4\1\0\14\4"+
    "\1\265\5\4\4\0\3\4\3\0\2\4\7\0\4\4"+
    "\1\0\10\4\1\266\11\4\4\0\3\4\3\0\2\4"+
    "\7\0\3\4\1\267\1\0\22\4\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\13\4\1\270\6\4\4\0"+
    "\3\4\3\0\2\4\7\0\4\4\1\0\3\4\1\271"+
    "\16\4\4\0\3\4\3\0\2\4\7\0\4\4\1\0"+
    "\13\4\1\272\6\4\4\0\3\4\3\0\2\4\7\0"+
    "\4\4\1\0\14\4\1\273\5\4\4\0\3\4\3\0"+
    "\2\4\7\0\3\4\1\274\1\0\22\4\4\0\3\4"+
    "\3\0\2\4\7\0\4\4\1\0\12\4\1\275\7\4"+
    "\4\0\3\4\3\0\2\4\7\0\4\4\1\0\7\4"+
    "\1\276\12\4\4\0\3\4\3\0\2\4\7\0\1\4"+
    "\1\277\2\4\1\0\22\4\4\0\3\4\3\0\2\4"+
    "\7\0\3\4\1\300\1\0\22\4\4\0\3\4\3\0"+
    "\2\4\7\0\4\4\1\0\13\4\1\301\6\4\4\0"+
    "\3\4\20\0\1\302\51\0\1\303\51\0\1\304\34\0"+
    "\2\4\7\0\4\4\1\0\14\4\1\305\5\4\4\0"+
    "\3\4\3\0\2\4\7\0\4\4\1\0\16\4\1\306"+
    "\3\4\4\0\3\4\3\0\2\4\7\0\3\4\1\307"+
    "\1\0\22\4\4\0\3\4\3\0\2\4\7\0\4\4"+
    "\1\0\4\4\1\310\15\4\4\0\3\4\3\0\2\4"+
    "\7\0\4\4\1\0\14\4\1\311\5\4\4\0\3\4"+
    "\3\0\2\4\7\0\4\4\1\0\13\4\1\312\6\4"+
    "\4\0\3\4\3\0\2\4\1\0\1\313\5\0\4\4"+
    "\1\0\22\4\4\0\3\4\3\0\2\4\7\0\4\4"+
    "\1\0\2\4\1\314\17\4\4\0\3\4\25\0\1\315"+
    "\43\0\1\316\71\0\1\317\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6636];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\3\1\1\11\20\1\4\11\2\1\2\11"+
    "\1\0\1\11\6\0\33\1\12\0\34\1\12\0\33\1"+
    "\1\11\1\1\6\0\1\11\1\0\26\1\2\0\1\11"+
    "\1\0\3\11\16\1\3\11\6\1\1\0\1\1\2\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[207];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { /* ignore */
          }
        case 54: break;
        case 8: 
          { return new Symbol(Simbolo.INICIO_ATRIBUTOS, yychar,yyline);
          }
        case 55: break;
        case 25: 
          { return new Symbol(Simbolo.OK, yychar,yyline);
          }
        case 56: break;
        case 43: 
          { return new Symbol(Simbolo.VALORES, yychar,yyline);
          }
        case 57: break;
        case 28: 
          { return new Symbol(Simbolo.IMAGEN, yychar,yyline);
          }
        case 58: break;
        case 42: 
          { return new Symbol(Simbolo.BOTON, yychar,yyline);
          }
        case 59: break;
        case 39: 
          { return new Symbol(Simbolo.REFRESH, yychar,yyline);
          }
        case 60: break;
        case 12: 
          { return new Symbol(Simbolo.KADENA, yychar,yyline, new String(yytext()));
          }
        case 61: break;
        case 23: 
          { return new Symbol(Simbolo.RUTA, yychar,yyline, new String(yytext()));
          }
        case 62: break;
        case 47: 
          { return new Symbol(Simbolo.ENCABEZADO_FIN, yychar,yyline);
          }
        case 63: break;
        case 38: 
          { return new Symbol(Simbolo.CREAR, yychar,yyline);
          }
        case 64: break;
        case 49: 
          { return new Symbol(Simbolo.LIBRERIAS, yychar,yyline);
          }
        case 65: break;
        case 21: 
          { return new Symbol(Simbolo.LEER, yychar,yyline);
          }
        case 66: break;
        case 30: 
          { return new Symbol(Simbolo.TITULO, yychar,yyline);
          }
        case 67: break;
        case 36: 
          { return new Symbol(Simbolo.CUERPO, yychar,yyline);
          }
        case 68: break;
        case 13: 
          { return new Symbol(Simbolo.SUB, yychar,yyline);
          }
        case 69: break;
        case 17: 
          { return new Symbol(Simbolo.HREF, yychar,yyline);
          }
        case 70: break;
        case 5: 
          { return new Symbol(Simbolo.PARRAFO, yychar,yyline);
          }
        case 71: break;
        case 22: 
          { return new Symbol(Simbolo.USUARIO, yychar,yyline);
          }
        case 72: break;
        case 10: 
          { return new Symbol(Simbolo.INICIO_SECCION, yychar,yyline);
          }
        case 73: break;
        case 40: 
          { return new Symbol(Simbolo.NUMERO, yychar,yyline);
          }
        case 74: break;
        case 32: 
          { return new Symbol(Simbolo.PASS, yychar,yyline);
          }
        case 75: break;
        case 14: 
          { return new Symbol(Simbolo.SUBT, yychar,yyline);
          }
        case 76: break;
        case 52: 
          { return new Symbol(Simbolo.VAR, yychar,yyline);
          }
        case 77: break;
        case 3: 
          { return new Symbol(Simbolo.INT, yychar,yyline, new String(yytext()));
          }
        case 78: break;
        case 2: 
          { System.out.println("Error lexico: "+yytext());
          }
        case 79: break;
        case 20: 
          { return new Symbol(Simbolo.TEXTO, yychar,yyline);
          }
        case 80: break;
        case 35: 
          { return new Symbol(Simbolo.ENCABEZADO, yychar,yyline);
          }
        case 81: break;
        case 27: 
          { return new Symbol(Simbolo.ENTRADA, yychar,yyline);
          }
        case 82: break;
        case 9: 
          { return new Symbol(Simbolo.FIN_ATRIBUTOS, yychar,yyline);
          }
        case 83: break;
        case 33: 
          { return new Symbol(Simbolo.SECCION_FIN, yychar,yyline);
          }
        case 84: break;
        case 48: 
          { return new Symbol(Simbolo.CUERPO_FIN, yychar,yyline);
          }
        case 85: break;
        case 44: 
          { return new Symbol(Simbolo.ACTUALIZAR, yychar,yyline);
          }
        case 86: break;
        case 19: 
          { return new Symbol(Simbolo.LISTA, yychar,yyline);
          }
        case 87: break;
        case 29: 
          { return new Symbol(Simbolo.ESTILOS, yychar,yyline);
          }
        case 88: break;
        case 1: 
          { return new Symbol(Simbolo.ALFANUMERICO, yychar,yyline, new String(yytext()));
          }
        case 89: break;
        case 31: 
          { return new Symbol(Simbolo.ANCHO, yychar,yyline);
          }
        case 90: break;
        case 24: 
          { return new Symbol(Simbolo.SECCION, yychar,yyline);
          }
        case 91: break;
        case 37: 
          { return new Symbol(Simbolo.ALTO, yychar,yyline);
          }
        case 92: break;
        case 41: 
          { return new Symbol(Simbolo.ELIMINAR, yychar,yyline);
          }
        case 93: break;
        case 16: 
          { return new Symbol(Simbolo.BOOL, yychar,yyline);
          }
        case 94: break;
        case 34: 
          { return new Symbol(Simbolo.MAIN, yychar,yyline);
          }
        case 95: break;
        case 50: 
          { return new Symbol(Simbolo.PRESS, yychar,yyline);
          }
        case 96: break;
        case 45: 
          { return new Symbol(Simbolo.USID, yychar,yyline);
          }
        case 97: break;
        case 18: 
          { return new Symbol(Simbolo.CARACTER, yychar,yyline);
          }
        case 98: break;
        case 53: 
          { return new Symbol(Simbolo.PKEY, yychar,yyline);
          }
        case 99: break;
        case 46: 
          { return new Symbol(Simbolo.MAIN_FIN, yychar,yyline);
          }
        case 100: break;
        case 7: 
          { return new Symbol(Simbolo.ASIGNACION, yychar,yyline);
          }
        case 101: break;
        case 6: 
          { return new Symbol(Simbolo.ENDLINE, yychar,yyline);
          }
        case 102: break;
        case 11: 
          { return new Symbol(Simbolo.FIN_SECCION, yychar,yyline);
          }
        case 103: break;
        case 51: 
          { return new Symbol(Simbolo.CONTRASENA, yychar,yyline);
          }
        case 104: break;
        case 15: 
          { return new Symbol(Simbolo.IDE, yychar,yyline);
          }
        case 105: break;
        case 26: 
          { return new Symbol(Simbolo.CLASE, yychar,yyline);
          }
        case 106: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(Simbolo.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
