
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 19 19:58:21 COT 2017
//----------------------------------------------------

package Modelos;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int NUMERO = 41;
  public static final int ACTUALIZAR = 24;
  public static final int BOTON = 28;
  public static final int ELIMINAR = 25;
  public static final int ALFANUMERICO = 42;
  public static final int ANCHO = 18;
  public static final int CUERPO = 21;
  public static final int INT = 43;
  public static final int SECCION_FIN = 50;
  public static final int INICIO_ATRIBUTOS = 13;
  public static final int CREAR = 22;
  public static final int USUARIO = 36;
  public static final int FIN_SECCION = 35;
  public static final int CARACTER = 40;
  public static final int CONTRASENA = 38;
  public static final int PASS = 30;
  public static final int BOOL = 10;
  public static final int ENDLINE = 11;
  public static final int TITULO = 16;
  public static final int OK = 6;
  public static final int MAIN = 2;
  public static final int LISTA = 7;
  public static final int REFRESH = 8;
  public static final int EOF = 0;
  public static final int VALORES = 45;
  public static final int ENCABEZADO_FIN = 48;
  public static final int ESTILOS = 26;
  public static final int CLASE = 33;
  public static final int error = 1;
  public static final int ENCABEZADO = 15;
  public static final int IDE = 37;
  public static final int ALTO = 19;
  public static final int CUERPO_FIN = 49;
  public static final int ASIGNACION = 12;
  public static final int INICIO_SECCION = 34;
  public static final int ENTRADA = 31;
  public static final int PKEY = 9;
  public static final int KADENA = 46;
  public static final int RUTA = 51;
  public static final int IMAGEN = 32;
  public static final int USID = 44;
  public static final int PARRAFO = 5;
  public static final int MAIN_FIN = 47;
  public static final int FIN_ATRIBUTOS = 14;
  public static final int HREF = 52;
  public static final int LIBRERIAS = 17;
  public static final int SUBT = 4;
  public static final int PRESS = 29;
  public static final int LEER = 23;
  public static final int TEXTO = 20;
  public static final int SECCION = 27;
  public static final int SUB = 3;
  public static final int VAR = 39;
}

